import Head from 'next/head'
import Header from '../components/Header'
import React, { useState } from 'react';
import AddNewDoc from '../components/AddNewDoc'
import Docs from '../components/Docs'
import Login from '../components/Login'
import {  getSession, useSession  } from 'next-auth/react'

export default function Home({session}) {

  if(!session) return <Login/>

  return (
    <div className=''>
      <Head>
        <title>Google Docs 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <AddNewDoc />

      <Docs />
    </div>
  )
}
