import Head from 'next/head'
import Header from '../components/Header'
import AddNewDoc from '../components/AddNewDoc'
import Docs from '../components/Docs'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Google Docs 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <AddNewDoc />

      <Docs />
    </div>
  )
}
